//! Replay system for playing back recorded game sessions
//!
//! The replay system loads `.evlog` files generated by simulations and plays them back
//! with interpolated positions, variable speed control, and behavior observation overlays.

mod loader;
mod state;
mod systems;
mod ui;

pub use loader::{load_replay, ReplayData, TickFrame, TimedEvent};
pub use state::ReplayState;
pub use systems::{
    replay_input_handler, replay_playback, replay_setup,
};
pub use ui::{
    ReplayEventMarker, ReplaySpeedDisplay, ReplayTimeDisplay, ReplayTimeline,
    PlayerGoalLabel, setup_replay_ui, update_replay_ui,
};

use bevy::prelude::*;

/// Resource to control replay mode activation
#[derive(Resource, Default)]
pub struct ReplayMode {
    /// Whether replay mode is active
    pub active: bool,
    /// Path to the .evlog file being replayed
    pub file_path: Option<String>,
}

impl ReplayMode {
    pub fn new(file_path: String) -> Self {
        Self {
            active: true,
            file_path: Some(file_path),
        }
    }
}

/// Run condition: returns true when replay mode is active
pub fn replay_active(replay_mode: Res<ReplayMode>) -> bool {
    replay_mode.active
}

/// Run condition: returns true when replay mode is NOT active (normal game)
pub fn not_replay_active(replay_mode: Res<ReplayMode>) -> bool {
    !replay_mode.active
}

/// Match info extracted from MatchStart event
#[derive(Debug, Clone, Default)]
pub struct MatchInfo {
    pub level: u32,
    pub level_name: String,
    pub left_profile: String,
    pub right_profile: String,
    pub seed: u64,
}
